set_property PACKAGE_PIN W5 [get_ports i_clock]							
	set_property IOSTANDARD LVCMOS33 [get_ports i_clock]
	create_clock -add -name sys_clk_pin -period 200.00 -waveform {0 100} [get_ports i_clock]

# Switches
set_property PACKAGE_PIN V17 [get_ports {i_reset}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_reset}]
set_property PACKAGE_PIN V16 [get_ports {i_rx_data}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_rx_data}]
set_property PACKAGE_PIN W16 [get_ports {i_tx_signal}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_tx_signal}]
set_property PACKAGE_PIN W17 [get_ports {i_tx_result}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_tx_result}]
set_property PACKAGE_PIN W15 [get_ports {i_parity}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {i_parity}]
set_property PACKAGE_PIN V15 [get_ports {o_rx_done}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_rx_done}]
set_property PACKAGE_PIN W14 [get_ports {o_rx_data}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_rx_data}]
set_property PACKAGE_PIN W13 [get_ports {o_parity}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_parity}]
set_property PACKAGE_PIN V2 [get_ports {o_tx_data}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_tx_data}]
set_property PACKAGE_PIN T3 [get_ports {o_tx_done}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {o_tx_done}]